# Generated by Django 3.0.4 on 2020-03-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppticket',
            old_name='supptype',
            new_name='subject',
        ),
    ]
