# Generated by Django 3.0.3 on 2020-02-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='datetime',
        ),
    ]
