# Generated by Django 3.0.3 on 2020-03-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_individualsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='customer',
            new_name='teacher',
        ),
    ]
