# Generated by Django 3.0.3 on 2020-03-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='individualsession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookings.IndividualSession'),
        ),
    ]
