# Generated by Django 3.0.3 on 2020-03-08 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bookings', '0010_auto_20200308_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
