# Generated by Django 3.0.3 on 2020-03-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_auto_20200308_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualsession',
            old_name='datetime',
            new_name='sessiontime',
        ),
    ]
