# Generated by Django 3.0.3 on 2020-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0012_auto_20200315_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image',
            field=models.ImageField(default='python-19.png', upload_to='profile_pics'),
        ),
    ]
